### PR TITLE
Images tiny optimize

### PR DESCRIPTION
**Pull request by JayJay1024**
只有一个Commit: 8582d22eb13b310433250212d7d77e0aa9b70e9f

图片压缩优化。
无损压缩，看起来和原来的相比没变模糊，压缩率还挺高的：

image

以后添加图片的话可以先在 https://tinypng.com/ 压缩一下 @wuminzhe @AsceticBear 

可以先merge到develop在l2me.com先看一下，再merge到main/master

### CODE REVIEW

**Comment by wi1dcard** [comment]
插一句：我不建议用任何在线网站压缩图片，因为存在被滥用的可能。我比较推荐本地的压缩工具ImageOptim，它集合了多种无损和有损的压缩算法，压缩率非常优秀。

**Comment by JayJay1024** [comment]
> 插一句：我不建议用任何在线网站压缩图片，因为存在被滥用的可能。我比较推荐本地的压缩工具ImageOptim，它集合了多种无损和有损的压缩算法，压缩率非常优秀。

嗯也有道理

**Comment by wi1dcard** [comment]
另外你合并的目标分支可能是错误的，此处有两种可能：

1. 该项目的分支管理出现了问题，导致之前有人直接合并到了 `main`，且你没有从 develop checkout。
2. `develop` 已经废弃、需要删除，该 PR 的目标分支选错了。

image

**Comment by JayJay1024** [comment]
> 另外你合并的目标分支可能是错误的，此处有两种可能：
> 
> 1. 该项目的分支管理出现了问题，导致之前有人直接合并到了 `main`，且你没有从 develop checkout。
> 2. `develop` 已经废弃、需要删除，该 PR 的目标分支选错了。
> 
> image

这个repo感觉是不是应该先push/merge到`develop`，这样上正式环境前还可以在 https://docs.crab.network.l2me.com/ 先看一下。看有些提交是直接merge到了main了，所以我更新main到最新，然后把develop更新到和main一样，再从develop checkout编辑更改

**Review by AsceticBear — APPROVED** [review]
这个仓库的分支管理之前有写混乱，Feature 直接合并到 master 上，并没有发挥出 develop 分支的作用，需要一个规范。@wuminzhe

**Review by HackFisher — CHANGES_REQUESTED** [review]
@JayJay1024 @wuminzhe If you are good with the conclusion that we should use the same CD convention as other repositories for more unified collaboration. (refer the discussion in latest slack education channel)

I'm changing the base branch to `main`, and will delete `develop` branch soon.

@JayJay1024 Also, please update the rules in https://github.com/darwinia-network/crab-docs/tree/main/.github/workflows

`main` for staging, and git tag for production.

**Comment by wuminzhe** [comment]
> @JayJay1024 @wuminzhe If you are good with the conclusion that we should use the same CD convention as other repositories for more unified collaboration. (refer the discussion in latest slack education channel)
> 
> I'm changing the base branch to `main`, and will delete `develop` branch soon.
> 
> @JayJay1024 Also, please update the rules in https://github.com/darwinia-network/crab-docs/tree/main/.github/workflows
> 
> `main` for staging, and git tag for production.

Ok.

**Comment by JayJay1024** [comment]
> @JayJay1024 @wuminzhe If you are good with the conclusion that we should use the same CD convention as other repositories for more unified collaboration. (refer the discussion in latest slack education channel)
> 
> I'm changing the base branch to `main`, and will delete `develop` branch soon.
> 
> @JayJay1024 Also, please update the rules in https://github.com/darwinia-network/crab-docs/tree/main/.github/workflows
> 
> `main` for staging, and git tag for production.

👌#33

**Review by HackFisher — APPROVED** [review]

**Pull request merged**
