### PR TITLE
Restructure

### PR DESCRIPTION
**Pull request by robinwei-itering**
1. Relocation of md & png files
2. Fix image links
3. Fix doc links
4. Update airdrop ts links

### CODE REVIEW

**Comment by AsceticBear** [comment]
Please update the latest para chain status here.
image

**Comment by AsceticBear** [comment]
This is an out-of-date link. I know It's very easy to create an invalid link if the link refers to the code repo directly.  Maybe using plain text runtime rather than the link is better. @1022ranji  Suggest fixing this in another separate pull quest later

image

**Comment by hujw77** [comment]
Is there a dev/staging environment to preview the docs?

**Comment by AsceticBear** [comment]
http://localhost:3000/substrate-based-crab-chain/crab-tokens

In the substrate-based-crab-chain section, no need to add token information about smart chain token info. The same with CKTON.

image

**Comment by AsceticBear** [comment]
> Is there a dev/staging environment to preview the docs?

I did not find it. Run in local env.

**Comment by AsceticBear** [comment]
Lack of Smart App section under Wallets

image

image

**Comment by robinwei-itering** [comment]
> Please update the latest para chain status here. image

fixed

**Comment by robinwei-itering** [comment]
> Lack of Smart App section under Wallets
> 
> image
> 
> image

fixed

**Comment by robinwei-itering** [comment]
> http://localhost:3000/substrate-based-crab-chain/crab-tokens
> 
> In the substrate-based-crab-chain section, no need to add token information about smart chain token info. The same with CKTON.
> 
> image

fixed

**Comment by robinwei-itering** [comment]
> This is an out-of-date link. I know It's very easy to create an invalid link if the link refers to the code repo directly. Maybe using plain text runtime rather than the link is better. @1022ranji Suggest fixing this in another separate pull quest later
> 
> image

fixed

**Review by HackFisher — APPROVED** [review]

**Comment by fewensa** [comment]
> Is there a dev/staging environment to preview the docs? cc @fewensa

Sorry, I'm miss some actions for this repository, currently you need follow slack darwinia-docs-edu channel.

**Pull request merged**
